"""
integrations/blender.py
========================
Blender handoff adapter.

Generates an export folder containing the verified image plus a
ready-to-run Blender Python script that:
  1. loads the image as a Blender image data-block
  2. creates a new material with a Principled BSDF
  3. wires the image into the Base Color input via an Image Texture node
  4. creates a simple plane mesh and assigns the material to it

Run it from Blender's Scripting tab, or headlessly with:
    blender --background --python blender_import.py
"""

import json
import shutil
from pathlib import Path

import config
from utils.file_utils import sanitize_filename

BLENDER_SCRIPT_TEMPLATE = '''\
"""
Auto-generated by Multimodal Image Generation Studio.
Run inside Blender (Scripting tab -> Run Script) or headlessly:
    blender --background --python {script_name}
"""
import bpy
import os

IMAGE_FILENAME = "{image_filename}"
script_dir = os.path.dirname(os.path.abspath(__file__))
image_path = os.path.join(script_dir, IMAGE_FILENAME)

# Load the image
img = bpy.data.images.load(image_path)

# Create material
mat = bpy.data.materials.new(name="GeneratedStudioMaterial")
mat.use_nodes = True
bsdf = mat.node_tree.nodes.get("Principled BSDF")
tex_node = mat.node_tree.nodes.new("ShaderNodeTexImage")
tex_node.image = img
mat.node_tree.links.new(bsdf.inputs["Base Color"], tex_node.outputs["Color"])

# Create a plane and assign the material
bpy.ops.mesh.primitive_plane_add(size=2)
plane = bpy.context.active_object
plane.name = "GeneratedStudioPlane"
if plane.data.materials:
    plane.data.materials[0] = mat
else:
    plane.data.materials.append(mat)

print("Imported '" + IMAGE_FILENAME + "' and applied it to a new plane's material.")
'''

INSTRUCTIONS = """\
BLENDER IMPORT INSTRUCTIONS
============================
1. Open Blender.
2. Go to the "Scripting" workspace tab.
3. Open "{script_name}" from this export folder (or paste its contents
   into a new text block).
4. Click "Run Script". This loads "{image_filename}" as an image
   data-block, creates a material with it wired into Base Color, and
   applies that material to a new plane so you can see it immediately.
5. Alternatively, run headlessly:
     blender --background --python {script_name}

metadata.json contains the full generation record for provenance.
"""


def export_for_blender(image_path: Path, metadata: dict, request_id: str) -> Path:
    export_dir = config.EXPORTS_DIR / "blender" / request_id
    export_dir.mkdir(parents=True, exist_ok=True)

    image_filename = sanitize_filename(image_path.name)
    dest_image = export_dir / image_filename
    shutil.copy2(image_path, dest_image)

    script_name = "blender_import.py"
    (export_dir / script_name).write_text(
        BLENDER_SCRIPT_TEMPLATE.format(script_name=script_name, image_filename=image_filename)
    )
    (export_dir / "metadata.json").write_text(json.dumps(metadata, indent=2))
    (export_dir / "README.txt").write_text(
        INSTRUCTIONS.format(script_name=script_name, image_filename=image_filename)
    )

    return export_dir
